"""Built-in capability-card snapshot.

These cards are intentionally conservative. They are seed data for local
planning, not a promise that every account/region/SDK entitlement supports
every feature at runtime.
"""

from typing import Any

BUILTIN_CAPABILITY_CARDS: list[dict[str, Any]] = [
    {
        "model_ref": {"provider": "openai", "model": "gpt-5.5", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": False,
        "supports_file_input": True,
        "supports_code_execution": False,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": ["temperature"],
        "known_edge_cases": ["High capability usually implies higher cost and latency."],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "coding", "agentic", "quality", "structured_output", "tool_use"],
        "cost_tier": "high",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "openai", "model": "gpt-5.4-mini", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_file_input": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "fast"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["low_latency", "low_cost", "tool_use", "structured_output"],
        "cost_tier": "low",
        "latency_tier": "fast",
        "quality_tier": "strong",
    },
    {
        "model_ref": {"provider": "anthropic", "model": "claude-opus-4-8", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_file_input": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["Check account data-retention and ZDR eligibility before sensitive use."],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "coding", "agentic", "critique", "quality"],
        "cost_tier": "high",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "anthropic", "model": "claude-sonnet-4-6", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-20",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_file_input": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["Check account data-retention and ZDR eligibility before sensitive use."],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "coding", "agentic", "critique", "quality", "tool_use"],
        "cost_tier": "medium",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "ollama", "model": "gpt-oss:120b", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-20",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text"],
        "modalities_output": ["text"],
        "supports_tools": False,
        "supports_structured_output": False,
        "supports_streaming": True,
        "supports_file_input": False,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": [
            "Ollama Cloud availability and session quotas can vary by account; run provider readiness checks before production use."
        ],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "coding", "quality", "privacy"],
        "cost_tier": "medium",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "ollama", "model": "glm-5.2", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-20",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text"],
        "modalities_output": ["text"],
        "supports_tools": False,
        "supports_structured_output": False,
        "supports_streaming": True,
        "supports_file_input": False,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": [
            "Ollama Cloud availability and quotas depend on the configured account; run readiness checks before production use."
        ],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "agentic", "coding", "privacy"],
        "cost_tier": "medium",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3.5-flash", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image", "audio", "video"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "fast"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["low_latency", "agentic", "coding", "multimodal", "tool_use", "structured_output"],
        "cost_tier": "low",
        "latency_tier": "fast",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3.1-flash-lite", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-19",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "modalities_input": ["text", "image", "audio", "video", "pdf"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "fast"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "benchmarks": {"source": "google_docs_2026_06_19"},
        "strengths": ["low_latency", "low_cost", "agentic", "multimodal", "structured_output"],
        "cost_tier": "low",
        "latency_tier": "fast",
        "quality_tier": "strong",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3-flash-preview", "stability": "preview", "source": "native"},
        "last_updated": "2026-06-19",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "modalities_input": ["text", "image", "audio", "video", "pdf"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["Preview model: avoid production unless explicitly allowed."],
        "benchmarks": {"source": "google_docs_2026_06_19"},
        "strengths": ["reasoning", "coding", "agentic", "multimodal", "quality", "tool_use"],
        "cost_tier": "medium",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3.1-pro-preview", "stability": "preview", "source": "native"},
        "last_updated": "2026-06-19",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "modalities_input": ["text", "image", "audio", "video"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["Preview model: avoid production unless explicitly allowed."],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "multimodal", "research", "quality"],
        "cost_tier": "medium",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
]

_NAN_SOURCE = "https://gist.github.com/686f6c61/8c05e9e6a1fa6062f5a23f56edac46af"

BUILTIN_CAPABILITY_CARDS.extend(
    [
        {
            "model_ref": {"provider": "nan", "model": "qwen3.6", "stability": "stable", "source": "native"},
            "last_updated": "2026-07-13",
            "context_window": 262_144,
            "model_kind": "chat",
            "modalities_input": ["text", "image"],
            "modalities_output": ["text"],
            "supports_tools": False,
            "supports_structured_output": True,
            "supports_streaming": True,
            "supports_file_input": False,
            "pricing": {"confidence": "unknown"},
            "data_retention": "provider_policy",
            "strengths": ["reasoning", "coding", "structured_output", "multimodal", "classification"],
            "routing_hints": {"reasoning": "enabled_by_default", "routing_status": "recommended"},
            "natural_profile": {
                "summary": "NaN default general-purpose chat model with image input, structured output, and optional thinking control.",
                "best_for": ["general_assistance", "coding", "classification", "vision"],
            },
            "known_edge_cases": [
                "A forced native tool probe returned finish_reason=tool_calls without tool call data on 2026-07-14."
            ],
            "evidence": {"provider_guide": _NAN_SOURCE},
            "cost_tier": "unknown",
            "latency_tier": "unknown",
            "quality_tier": "unknown",
        },
        {
            "model_ref": {
                "provider": "nan",
                "model": "deepseek-v4-flash",
                "stability": "stable",
                "source": "native",
            },
            "last_updated": "2026-07-13",
            "context_window": 1_000_000,
            "model_kind": "chat",
            "modalities_input": ["text"],
            "modalities_output": ["text"],
            "supports_tools": True,
            "supports_structured_output": True,
            "supports_streaming": True,
            "pricing": {"confidence": "unknown"},
            "data_retention": "provider_policy",
            "strengths": ["reasoning", "long_context", "coding", "tool_use", "classification"],
            "routing_hints": {"reasoning_effort": ["low", "medium", "high"], "routing_status": "specialized"},
            "natural_profile": {
                "summary": "Text reasoning model with a one-million-token context and controllable reasoning effort.",
                "best_for": ["long_context", "reasoning", "coding", "classification"],
            },
            "evidence": {"provider_guide": _NAN_SOURCE},
            "cost_tier": "unknown",
            "latency_tier": "unknown",
            "quality_tier": "unknown",
        },
        {
            "model_ref": {"provider": "nan", "model": "mimo-v2.5", "stability": "stable", "source": "native"},
            "last_updated": "2026-07-13",
            "context_window": 1_000_000,
            "model_kind": "chat",
            "modalities_input": ["text", "image", "audio"],
            "modalities_output": ["text"],
            "supports_tools": True,
            "supports_structured_output": True,
            "supports_streaming": True,
            "pricing": {"confidence": "unknown"},
            "data_retention": "provider_policy",
            "strengths": ["reasoning", "long_context", "tool_use", "multimodal", "audio_understanding"],
            "routing_hints": {"reasoning": "always_enabled", "routing_status": "specialized"},
            "known_edge_cases": ["Thinking is always enabled; very small output-token limits can truncate useful answers."],
            "natural_profile": {
                "summary": "Long-context multimodal chat model that accepts text, images, and native audio and always reasons.",
                "best_for": ["long_context", "audio_understanding", "vision", "reasoning"],
            },
            "evidence": {"provider_guide": _NAN_SOURCE},
            "cost_tier": "unknown",
            "latency_tier": "unknown",
            "quality_tier": "unknown",
        },
        {
            "model_ref": {"provider": "nan", "model": "gemma4", "stability": "stable", "source": "native"},
            "last_updated": "2026-07-13",
            "context_window": 262_144,
            "model_kind": "chat",
            "modalities_input": ["text", "image"],
            "modalities_output": ["text"],
            "supports_tools": True,
            "supports_structured_output": True,
            "supports_streaming": True,
            "pricing": {"confidence": "unknown"},
            "data_retention": "provider_policy",
            "strengths": ["reasoning", "structured_output", "multimodal", "classification"],
            "routing_hints": {"reasoning": "opt_in", "routing_status": "specialized"},
            "known_edge_cases": ["NaN's compatibility layer translates the model-specific tool syntax."],
            "natural_profile": {
                "summary": "Vision-capable chat model with structured output and opt-in thinking.",
                "best_for": ["vision", "structured_output", "classification"],
            },
            "evidence": {"provider_guide": _NAN_SOURCE},
            "cost_tier": "unknown",
            "latency_tier": "unknown",
            "quality_tier": "unknown",
        },
        {
            "model_ref": {
                "provider": "nan",
                "model": "qwen3-embedding",
                "stability": "stable",
                "source": "native",
            },
            "last_updated": "2026-07-13",
            "model_kind": "embedding",
            "modalities_input": ["text"],
            "modalities_output": ["embedding"],
            "supports_embeddings": True,
            "embedding_dimensions": 4096,
            "embedding_input_modalities": ["text"],
            "supports_streaming": False,
            "pricing": {"confidence": "unknown"},
            "data_retention": "provider_policy",
            "strengths": ["embeddings", "semantic_search", "rag", "classification"],
            "routing_hints": {
                "routing_status": "specialized",
                "embedding_dimensions_mode": "fixed",
            },
            "natural_profile": {"summary": "NaN text embedding model with a fixed 4096-dimensional output."},
            "evidence": {"provider_guide": _NAN_SOURCE},
            "quality_tier": "embedding",
        },
        {
            "model_ref": {"provider": "nan", "model": "rerank", "stability": "stable", "source": "native"},
            "last_updated": "2026-07-13",
            "model_kind": "reranker",
            "modalities_input": ["text"],
            "modalities_output": ["ranking"],
            "supports_streaming": False,
            "pricing": {"confidence": "unknown"},
            "strengths": ["reranking", "rag", "classification"],
            "routing_hints": {"endpoint": "/v1/rerank", "routing_status": "specialized"},
            "evidence": {"provider_guide": _NAN_SOURCE},
        },
        {
            "model_ref": {"provider": "nan", "model": "kokoro", "stability": "stable", "source": "native"},
            "last_updated": "2026-07-13",
            "model_kind": "tts",
            "modalities_input": ["text"],
            "modalities_output": ["audio"],
            "supports_streaming": False,
            "pricing": {"confidence": "unknown"},
            "strengths": ["text_to_speech"],
            "routing_hints": {"routing_status": "specialized"},
            "evidence": {"provider_guide": _NAN_SOURCE},
        },
        {
            "model_ref": {"provider": "nan", "model": "whisper", "stability": "stable", "source": "native"},
            "last_updated": "2026-07-13",
            "model_kind": "transcription",
            "modalities_input": ["audio"],
            "modalities_output": ["text"],
            "supports_streaming": False,
            "pricing": {"confidence": "unknown"},
            "strengths": ["speech_to_text", "audio_transcription"],
            "routing_hints": {"routing_status": "specialized"},
            "evidence": {"provider_guide": _NAN_SOURCE},
        },
        {
            "model_ref": {
                "provider": "nan",
                "model": "flux-2-klein",
                "stability": "stable",
                "source": "native",
            },
            "last_updated": "2026-07-13",
            "model_kind": "image_generation",
            "modalities_input": ["text", "image"],
            "modalities_output": ["image"],
            "supports_streaming": False,
            "pricing": {"confidence": "unknown"},
            "strengths": ["image_generation", "image_editing"],
            "routing_hints": {"routing_status": "specialized"},
            "evidence": {"provider_guide": _NAN_SOURCE},
        },
    ]
)
