"""Built-in capability-card snapshot.

These cards are intentionally conservative. They are seed data for local
planning, not a promise that every account/region/SDK entitlement supports
every feature at runtime.
"""

BUILTIN_CAPABILITY_CARDS = [
    {
        "model_ref": {"provider": "openai", "model": "gpt-5.5", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": False,
        "supports_file_input": True,
        "supports_code_execution": False,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["High capability usually implies higher cost and latency."],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "coding", "agentic", "quality", "structured_output", "tool_use"],
        "cost_tier": "high",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "openai", "model": "gpt-5.4-mini", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_file_input": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "fast"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["low_latency", "low_cost", "tool_use", "structured_output"],
        "cost_tier": "low",
        "latency_tier": "fast",
        "quality_tier": "strong",
    },
    {
        "model_ref": {"provider": "anthropic", "model": "claude-opus-4-8", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_file_input": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["Check account data-retention and ZDR eligibility before sensitive use."],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "coding", "agentic", "critique", "quality"],
        "cost_tier": "high",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3.5-flash", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-18",
        "context_window": None,
        "max_output_tokens": None,
        "modalities_input": ["text", "image", "audio", "video"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "fast"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["low_latency", "agentic", "coding", "multimodal", "tool_use", "structured_output"],
        "cost_tier": "low",
        "latency_tier": "fast",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3.1-flash-lite", "stability": "stable", "source": "native"},
        "last_updated": "2026-06-19",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "modalities_input": ["text", "image", "audio", "video", "pdf"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "fast"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "benchmarks": {"source": "google_docs_2026_06_19"},
        "strengths": ["low_latency", "low_cost", "agentic", "multimodal", "structured_output"],
        "cost_tier": "low",
        "latency_tier": "fast",
        "quality_tier": "strong",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3-flash-preview", "stability": "preview", "source": "native"},
        "last_updated": "2026-06-19",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "modalities_input": ["text", "image", "audio", "video", "pdf"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["Preview model: avoid production unless explicitly allowed."],
        "benchmarks": {"source": "google_docs_2026_06_19"},
        "strengths": ["reasoning", "coding", "agentic", "multimodal", "quality", "tool_use"],
        "cost_tier": "medium",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
    {
        "model_ref": {"provider": "google", "model": "gemini-3.1-pro-preview", "stability": "preview", "source": "native"},
        "last_updated": "2026-06-19",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "modalities_input": ["text", "image", "audio", "video"],
        "modalities_output": ["text"],
        "supports_tools": True,
        "supports_structured_output": True,
        "supports_streaming": True,
        "supports_web": True,
        "supports_file_input": True,
        "supports_code_execution": True,
        "pricing": {"confidence": "unknown"},
        "latency_profile": {"tier": "medium"},
        "data_retention": "provider_policy",
        "zdr_eligible": None,
        "regions": [],
        "unsupported_params": [],
        "known_edge_cases": ["Preview model: avoid production unless explicitly allowed."],
        "benchmarks": {"source": "seed_snapshot"},
        "strengths": ["reasoning", "multimodal", "research", "quality"],
        "cost_tier": "medium",
        "latency_tier": "medium",
        "quality_tier": "frontier",
    },
]
